config/routes.rb
Rails.application.routes.draw do
  resources :foods
  root "foods#index"
end

app/models/food.rb
class Food < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  def index
    @foods = Food.all
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    respond_to do |format|
    @food.save
    format.html { redirect_to foods_path }
    end
  end

  def edit
    @food = Food.find(params[:id])
  end

  def update
    @food = Food.find(params[:id])
    respond_to do |format|
    @food.update(food_params)
    format.html { redirect_to foods_path }
    end
  end

  def show
    @food = Food.find(params[:id])
  end

  def destroy
    @food = Food.find(params[:id])
    respond_to do |format|
    @food.destroy
    format.html { redirect_to foods_path }
    end
  end


  private

  def food_params
      params.require(:food).permit(:description, :best_ingredient, :rating, :tried)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/edit.html.erb
<h1>Edit Food<h1>

<%= form_for(@food) do |t| %>

Description:
<%= t.text_field :description %>
Best Ingredient:
<%= t.text_field :best_ingredient %>
Rating:
<%= t.number_field :rating %>
Tried?:
<%= t.check_box :tried %>
<%= t.submit %>

<% end %>

app/views/foods/index.html.erb
<h1>Foods</h1>
<%= link_to "Add New Food", new_food_path %>

<table>
  <thead>
    <tr>
      <th>
        Type
      </th>
      <th>
        Best Ingredient
      </th>
      <th>
        Rating
      </th>
      <th>
        Tried it?
      </th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td>
          <%= link_to (food.description), food_path(food) %>
        </td>
        <td>
          <%= food.best_ingredient %>
        </td>
        <td>
          <%= food.rating %>
        </td>
        <td>
          <%= food.tried %>
        </td>
        <td>
          <%= link_to "Edit", edit_food_path(food) %>
        </td>
        <td>
          <%= link_to "Delete", food, method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/foods/new.html.erb
<h1>New Food<h1>

<%= form_for(@food) do |t| %>

Description:
<%= t.text_field :description %>
Best Ingredient:
<%= t.text_field :best_ingredient %>
Rating:
<%= t.number_field :rating %>
Tried?:
<%= t.check_box :tried %>
<%= t.submit %>

<% end %>

app/views/foods/show.html.erb
<h1><%= @food.description %></h1>

Best Ingredient:
<%= @food.best_ingredient %>

Rating:
<%= @food.rating %>


<%= link_to "Edit", edit_food_path(@food) %>
<%= link_to "Delete", @food, method: :delete %>
<%= link_to "Back to Foods", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crud4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>